DELIMITER $$
CREATE TRIGGER delete_accounts_on_user_delete
AFTER DELETE ON Users
FOR EACH ROW
BEGIN
    DELETE FROM Cards WHERE IBAN IN (SELECT IBAN FROM Accounts WHERE UserID = OLD.UserID);
    DELETE FROM Accounts WHERE UserID = OLD.UserID;
END$$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER delete_cards_on_accounts_delete
AFTER DELETE ON Accounts
FOR EACH ROW
BEGIN
    DELETE FROM Cards WHERE IBAN = OLD.IBAN;
END$$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER before_insert_cards
BEFORE INSERT ON Cards
FOR EACH ROW
BEGIN
    IF NEW.CVV IS NULL THEN
        SET NEW.CVV = (SELECT IFNULL(MAX(CVV), -1) + 1 FROM Cards) % 1000;
    END IF;
END$$
DELIMITER ;


DELIMITER $$
CREATE TRIGGER check_age_before_insert
BEFORE INSERT ON Users
FOR EACH ROW
BEGIN
    IF NEW.Date_of_Birth > CURDATE() - INTERVAL 18 YEAR THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'You must be at least 18 years old.';
    END IF;
END$$
DELIMITER ;